jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion
        }}"
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 17
        server-id: oss.sonatype.org
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_OPTS: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
          --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
        MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      name: Publish package
      run: mvn --batch-mode clean deploy -P central-deploy -DskipTests=true -pl .,amazon-s3,appengine,benchmarks,cdi,cloud-datastore,cloud-spanner,cloud-storage,console,core,dynamodb,hazelcast,junit,kotlin,mongodb,redis,servlet,shiro,slack,spock,spring-core,spring-security,spring-web,test-harness,testing,spring-boot,spring-boot/autoconfigure,spring-boot/starter,spring-boot/starter-actuator,spring-boot/starter-console,spring-boot/starter-core,spring-boot/starter-security,spring-boot/starter-thymeleaf,spring-boot/starter-webmvc
name: release-to-maven-central
on:
  repository_dispatch:
    types: trigger-ga___maven-central-release.yml
