jobs:
  sbom-generation:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      id: sbom
      uses: advanced-security/sbom-generator-action@v0.0.1
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: ${{steps.sbom.outputs.fileName }}
name: SBOM Generator
on:
  repository_dispatch:
    types: trigger-ga___sbom-generation.yml
permissions: read-all
