jobs:
  SBOM-upload:
    permissions:
      contents: write
      id-token: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Generate SBOM
      run: 'curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64

        chmod +x $RUNNER_TEMP/sbom-tool

        $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv
        1.0.0 -ps OwnerName -nsb https://sbom.togglz.org -V Verbose

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: _manifest/spdx_2.2
    - continue-on-error: true
      name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@v0.0.1
      with:
        filePath: _manifest/spdx_2.2/
name: SBOM upload
on:
  repository_dispatch:
    types: trigger-ga___sbom-upload.yml
